##Recuperartodas las peliculas 
GET http://localhost:3000/movies

###Recuperar una pelicula por id 
GET http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

###Recuperar una pelicula por un genero
GET http://localhost:3000/movies?genre=action

### Crear una pelicula 
POST http://localhost:3000/movies
Content-Type: application/json 

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Frod Coppola",
  "duration": 175,
  "poster": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQjkxk1HXZqweCR7dcKnjQEI5ZjKxiyNMUqZxFLE99AQlGM5f9r",
  "genre": [
    "Crime",
    "Drama"
  ]
}

###Actualizar una pelicula 
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 1993
}